### ISSUE TITLE
Can not show codes correctly

### ISSUE THREAD

**Issue by Luxios22** [iOliverNguyen/chatgpt-box-extension#3]
![image](https://user-images.githubusercontent.com/67457897/206609750-0570308b-d038-4c39-9a40-e221b5d91148.png)

can not show the above code correctly in beautiful code blocks.

**Comment by iOliverNguyen** [comment]
Thanks for your report! This is definitely fixed soon.

**Comment by iOliverNguyen** [comment]
The latest update, v0.2.0, fix showing code. Please download again.
